services:
  ros:
    image: avercromxd/ros2_vdb:latest
    container_name: ros2_vdb

    volumes:
      - ${PWD}/..:/home/dockerian
      - ~/.Xauthority:/home/dockerian/.Xauthority
    
    # Environment variables
    environment:
      - XAUTHORITY=~/.Xauthority
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    
    # Network and system settings
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    
    # Working directory
    working_dir: /home/dockerian
    
    # Interactive mode
    stdin_open: true
    tty: true
